using Business.Abstract;
using Core.Entities.Concrete;
using Core.Utilities.Results;
using Core.Utilities.Security.Hashing;
using Core.Utilities.Security.JWT;
using DataAccess.Abstract;
using Entities.Concrete;
using System.Collections.Generic;

namespace Business.Concrete
{
    public class BusinessUserManager : IBusinessUserService
    {
        private readonly IBusinessUserDal _businessUserDal;
        private readonly ITokenHelper _tokenHelper;

        public BusinessUserManager(IBusinessUserDal businessUserDal, ITokenHelper tokenHelper)
        {
            _businessUserDal = businessUserDal;
            _tokenHelper = tokenHelper;
        }

        public IDataResult<BusinessUser> Add(BusinessUserDto businessUserDto)
        {
            HashingHelper.CreatePasswordHash(businessUserDto.Password, out byte[] passwordHash, out byte[] passwordSalt);

            var user = new BusinessUser
            {
                Email = businessUserDto.Email,
                PasswordHash = passwordHash,
                PasswordSalt = passwordSalt,
                FirstName = businessUserDto.FirstName,
                LastName = businessUserDto.LastName,
                CompanyAddress = businessUserDto.CompanyAddress,
                CompanyName = businessUserDto.CompanyName,
                // Id is auto-generated by SQL
            };

            _businessUserDal.Add(user);
            return new SuccessDataResult<BusinessUser>(user, "Kayıt başarılı.");
        }

        public IDataResult<AccessToken> CreateAccessToken(BusinessUser user)
        {
            var accessToken = _tokenHelper.CreateTokenForUser(user);
            return new SuccessDataResult<AccessToken>(accessToken);
        }

        public IResult Delete(int id)
        {
            _businessUserDal.Delete(id);
            return new SuccessResult("Kullanıcı silindi.");
        }

        public IDataResult<List<BusinessUser>> GetAll()
        {
            // Call the custom method we created in EfBusinessUserDal for optimized DTO projection
            return new SuccessDataResult<List<BusinessUser>>(_businessUserDal.GetAllBusinessUserDetails());
        }

        public IDataResult<BusinessUser> GetById(int id)
        {
            var user = _businessUserDal.Get(p => p.Id == id);
            if (user == null)
            {
                return new ErrorDataResult<BusinessUser>("Kullanıcı bulunamadı.");
            }
            return new SuccessDataResult<BusinessUser>(user, "Kullanıcı getirildi.");
        }

        public IDataResult<BusinessUser> ResetPassword(BusinessUserPasswordResetDto businessUser)
        {
            var existingUser = _businessUserDal.Get(x => x.Email == businessUser.Email);
            if (existingUser == null)
                return new ErrorDataResult<BusinessUser>("Kullanıcı bulunamadı.");

            HashingHelper.CreatePasswordHash(businessUser.Password, out byte[] passwordHash, out byte[] passwordSalt);

            existingUser.PasswordHash = passwordHash;
            existingUser.PasswordSalt = passwordSalt;

            _businessUserDal.Update(existingUser);

            return new SuccessDataResult<BusinessUser>(existingUser, "Şifre sıfırlandı.");
        }

        public IResult Update(BusinessUser businessUser, int id)
        {
            // Usually, you should fetch the user first to ensure it exists, but this works if you trust the input object
            if (businessUser.Id != id) businessUser.Id = id;

            _businessUserDal.Update(businessUser);
            return new SuccessResult("Kullanıcı güncellendi.");
        }

        public IDataResult<BusinessUser> UserLogin(BusinessUserLoginDto userForLoginDto)
        {
            var userToCheck = _businessUserDal.Get(x => x.Email == userForLoginDto.Email);
            if (userToCheck == null)
            {
                return new ErrorDataResult<BusinessUser>("Kullanıcı bulunamadı.");
            }

            if (!HashingHelper.VerifyPasswordHash(userForLoginDto.Password, userToCheck.PasswordHash, userToCheck.PasswordSalt))
            {
                return new ErrorDataResult<BusinessUser>("Şifre yanlış");
            }

            return new SuccessDataResult<BusinessUser>(userToCheck, "Giriş başarılı.");
        }
    }
}